import Header from "../components/youtube/Header";   
import Main from "../components/youtube/Main";   
import Head from 'next/Head';

export default function Home() {
  return (
    <div> 
      <Head>
        <title>YouTube Clone</title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Main />
      </main>
    </div>
  )
}
